In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

N = 20
vars = ["x", "y", "z"]

df = pd.DataFrame([np.round(np.random.random(3)) for _ in range(N)], 
    columns=vars).astype(int)

states = {
    "x": range(2),
    "y": range(2),
    "z": range(2)
}

res = {
    "x -> z -> y": 0,
    "x -> z <- y": 0,
    "x <- z -> y": 0,
    "x <- z <- y": 0,
}

df

    x  y  z
0   1  1  1
1   0  0  1
2   0  1  0
3   1  0  0
4   1  1  0
5   0  1  1
6   0  1  1
7   1  1  1
8   0  1  0
9   1  0  0
10  0  0  1
11  1  1  0
12  1  0  0
13  1  0  1
14  0  1  0
15  0  1  0
16  0  1  0
17  1  0  1
18  1  1  0
19  1  0  1

In [2]:

def log_likelihood(vars, pa):
    logl = 0
    for var in vars:
        for i in states[var]:
            if len(pa[var]) > 0:
                for parent in pa[var]:
                    for j in states[parent]:
                        logl += df[(df[var] == i) & (df[parent] == j)].shape[0] * np.log(df[(df[var] == i) & (df[parent] == j)].shape[0] / df[df[parent] == j].shape[0])

            else:
                logl += df[df[var] == i].shape[0] * np.log(df[df[var] == i].shape[0] / df.shape[0])
    return logl

res["x -> z -> y"] = log_likelihood(vars, {"x": [], "z": ["x"], "y": ["z"]})
res["x -> z <- y"] = log_likelihood(vars, {"x": [], "z": ["x", "y"], "y": []})
res["x <- z -> y"] = log_likelihood(vars, {"x": ["z"], "z": [], "y": ["z"]})
res["x <- z <- y"] = log_likelihood(vars, {"x": ["z"], "z": ["y"], "y": []})

res

{'x -> z -> y': -40.152665077605896,
 'x -> z <- y': -53.91544135187767,
 'x <- z -> y': -40.152665077605896,
 'x <- z <- y': -40.15266507760589}

In [3]:
max(res)

'x <- z <- y'